services:
  kafka:
    image: apache/kafka:4.0.0
    container_name: kafka
    ports:
      - "9092:9092"
      - "9093:9093"
      - "9094:9094"
    networks:
      - kafka-network
    environment:
      CLUSTER_ID: _MJ5OwQ6TY-c9f8QqIaqcw
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3

  kafka-ui:
    image: kafbat/kafka-ui:v1.3.0
    container_name: kafkaui
    depends_on:
      - kafka
    ports:
      - "8081:8080"
    networks:
      - kafka-network
    environment:
      DYNAMIC_CONFIG_ENABLED: "true"
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092

  opensearch:
    image: opensearchproject/opensearch:3.1.0
    ports:
      - "9200:9200"
      - "9600:9600"
    networks:
      - kafka-network
    environment:
      OPENSEARCH_INITIAL_ADMIN_PASSWORD: 4dM1n.P@ssw0rd
      discovery.type: single-node
      plugins.security.disabled: true

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:3.1.0
    ports:
      - "5601:5601"
    networks:
      - kafka-network
    environment:
      OPENSEARCH_HOSTS: '["http://opensearch:9200"]'
      DISABLE_SECURITY_DASHBOARDS_PLUGIN: "true"

networks:
  kafka-network:
    driver: bridge